-- ============================================================
-- config/schema.sql — generated by scripts/generate-schema.js
--
-- Single source of truth for the Omie → Supabase database.
-- Re-run after any change to config/omie-tables.js.
--
-- Every Omie field is a typed, real Postgres column. NO raw / NO
-- jsonb columns. Arrays of objects (line items, characteristics,
-- etc.) are pivoted into dedicated child tables linked via FK.
--
-- This file is idempotent — `create table if not exists` and
-- `add column if not exists` everywhere. Designed to be pasted
-- straight into the Supabase SQL Editor on a fresh database.
-- ============================================================

-- ──────────────────────────────────────────────────────────────────
-- omie_clients  (phase 0 (legacy), tier critical)
-- Customers & suppliers (CRM master)
-- Endpoint: geral/clientes/ListarClientes
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_clients (
  codigo_cliente_omie bigint primary key,
  codigo_cliente_integracao text,
  razao_social text,
  nome_fantasia text,
  cnpj_cpf text,
  inscricao_estadual text,
  inscricao_municipal text,
  inscricao_suframa text,
  email text,
  homepage text,
  cnae text,
  tipo_atividade text,
  optante_simples_nacional boolean,
  produtor_rural boolean,
  contribuinte text,
  exterior boolean,
  pessoa_fisica boolean,
  bloqueado boolean,
  bloquear_faturamento boolean,
  inativo boolean,
  observacao text,
  pais text,
  estado text,
  cidade text,
  cidade_ibge text,
  bairro text,
  endereco text,
  endereco_numero text,
  complemento text,
  cep text,
  codigo_pais text,
  telefone1_ddd text,
  telefone1_numero text,
  telefone2_ddd text,
  telefone2_numero text,
  fax_ddd text,
  fax_numero text,
  contato text,
  cargo_contato text,
  valor_limite_credito numeric,
  pessoa_fisica_dt_nasc date,
  pessoa_fisica_sexo text,
  pessoa_fisica_estado_civil text,
  banco_codigo text,
  banco_agencia text,
  banco_conta_corrente text,
  banco_doc_titular text,
  banco_nome_titular text,
  banco_transf_padrao boolean,
  entrega_endereco text,
  entrega_numero text,
  entrega_complemento text,
  entrega_bairro text,
  entrega_cidade text,
  entrega_estado text,
  entrega_cep text,
  entrega_codigo_pais text,
  rec_codigo_vendedor bigint,
  rec_codigo_transportador bigint,
  rec_gerar_boletos boolean,
  rec_numero_parcelas numeric,
  rec_observacoes text,
  tipo_assinante text,
  info_cint text,
  info_imp_api text,
  info_dt_inc date,
  info_hr_inc text,
  info_user_inc text,
  info_dt_alt date,
  info_hr_alt text,
  info_user_alt text,
  ativo boolean,
  synced_at timestamptz default now()
);

alter table omie_clients
  add column if not exists codigo_cliente_integracao text,
  add column if not exists razao_social text,
  add column if not exists nome_fantasia text,
  add column if not exists cnpj_cpf text,
  add column if not exists inscricao_estadual text,
  add column if not exists inscricao_municipal text,
  add column if not exists inscricao_suframa text,
  add column if not exists email text,
  add column if not exists homepage text,
  add column if not exists cnae text,
  add column if not exists tipo_atividade text,
  add column if not exists optante_simples_nacional boolean,
  add column if not exists produtor_rural boolean,
  add column if not exists contribuinte text,
  add column if not exists exterior boolean,
  add column if not exists pessoa_fisica boolean,
  add column if not exists bloqueado boolean,
  add column if not exists bloquear_faturamento boolean,
  add column if not exists inativo boolean,
  add column if not exists observacao text,
  add column if not exists pais text,
  add column if not exists estado text,
  add column if not exists cidade text,
  add column if not exists cidade_ibge text,
  add column if not exists bairro text,
  add column if not exists endereco text,
  add column if not exists endereco_numero text,
  add column if not exists complemento text,
  add column if not exists cep text,
  add column if not exists codigo_pais text,
  add column if not exists telefone1_ddd text,
  add column if not exists telefone1_numero text,
  add column if not exists telefone2_ddd text,
  add column if not exists telefone2_numero text,
  add column if not exists fax_ddd text,
  add column if not exists fax_numero text,
  add column if not exists contato text,
  add column if not exists cargo_contato text,
  add column if not exists valor_limite_credito numeric,
  add column if not exists pessoa_fisica_dt_nasc date,
  add column if not exists pessoa_fisica_sexo text,
  add column if not exists pessoa_fisica_estado_civil text,
  add column if not exists banco_codigo text,
  add column if not exists banco_agencia text,
  add column if not exists banco_conta_corrente text,
  add column if not exists banco_doc_titular text,
  add column if not exists banco_nome_titular text,
  add column if not exists banco_transf_padrao boolean,
  add column if not exists entrega_endereco text,
  add column if not exists entrega_numero text,
  add column if not exists entrega_complemento text,
  add column if not exists entrega_bairro text,
  add column if not exists entrega_cidade text,
  add column if not exists entrega_estado text,
  add column if not exists entrega_cep text,
  add column if not exists entrega_codigo_pais text,
  add column if not exists rec_codigo_vendedor bigint,
  add column if not exists rec_codigo_transportador bigint,
  add column if not exists rec_gerar_boletos boolean,
  add column if not exists rec_numero_parcelas numeric,
  add column if not exists rec_observacoes text,
  add column if not exists tipo_assinante text,
  add column if not exists info_cint text,
  add column if not exists info_imp_api text,
  add column if not exists info_dt_inc date,
  add column if not exists info_hr_inc text,
  add column if not exists info_user_inc text,
  add column if not exists info_dt_alt date,
  add column if not exists info_hr_alt text,
  add column if not exists info_user_alt text,
  add column if not exists ativo boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_clients_synced on omie_clients (synced_at);

-- child of omie_clients: array `tags`
create table if not exists omie_client_tags (
  omie_id text not null,
  codigo_cliente_omie bigint not null,
  tag text,
  synced_at timestamptz default now(),
  primary key (codigo_cliente_omie, omie_id)
);

alter table omie_client_tags
  add column if not exists tag text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_client_tags_codigo_cliente_omie on omie_client_tags (codigo_cliente_omie);
create index if not exists idx_omie_client_tags_synced on omie_client_tags (synced_at);

-- child of omie_clients: array `caracteristicas`
create table if not exists omie_client_caracteristicas (
  omie_id text not null,
  codigo_cliente_omie bigint not null,
  cod_caract text,
  caracteristica text,
  conteudo text,
  synced_at timestamptz default now(),
  primary key (codigo_cliente_omie, omie_id)
);

alter table omie_client_caracteristicas
  add column if not exists cod_caract text,
  add column if not exists caracteristica text,
  add column if not exists conteudo text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_client_caracteristicas_codigo_cliente_omie on omie_client_caracteristicas (codigo_cliente_omie);
create index if not exists idx_omie_client_caracteristicas_synced on omie_client_caracteristicas (synced_at);

-- child of omie_clients: array `contatos`
create table if not exists omie_client_contatos (
  omie_id text not null,
  codigo_cliente_omie bigint not null,
  cod_contato text,
  nome text,
  sobrenome text,
  cargo text,
  email text,
  fone text,
  cpf text,
  synced_at timestamptz default now(),
  primary key (codigo_cliente_omie, omie_id)
);

alter table omie_client_contatos
  add column if not exists cod_contato text,
  add column if not exists nome text,
  add column if not exists sobrenome text,
  add column if not exists cargo text,
  add column if not exists email text,
  add column if not exists fone text,
  add column if not exists cpf text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_client_contatos_codigo_cliente_omie on omie_client_contatos (codigo_cliente_omie);
create index if not exists idx_omie_client_contatos_synced on omie_client_contatos (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_orders  (phase 0 (legacy), tier critical)
-- Sales orders
-- Endpoint: produtos/pedido/ListarPedidos
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_orders (
  codigo_pedido bigint primary key,
  codigo_pedido_integracao text,
  numero_pedido text,
  codigo_cliente bigint,
  codigo_cenario bigint,
  codigo_local_estoque bigint,
  codigo_parcela text,
  data_previsao date,
  etapa text,
  qtde_itens numeric,
  origem_pedido text,
  pedido_status text,
  codigo_categoria text,
  codigo_conta_corrente bigint,
  codigo_departamento text,
  codigo_tipo_documento text,
  codigo_vendedor bigint,
  codigo_projeto bigint,
  consumidor_final text,
  enviar_email boolean,
  numero_pedido_cliente text,
  obs_venda text,
  obs_internas text,
  utilizar_emails text,
  codigo_transportadora bigint,
  modalidade_frete text,
  placa_veiculo text,
  qtde_volumes numeric,
  peso_bruto numeric,
  peso_liquido numeric,
  uf_veiculo text,
  valor_frete numeric,
  especie_volumes text,
  marca_volumes text,
  valor_mercadorias numeric,
  valor_total_pedido numeric,
  valor_descontos numeric,
  valor_acrescimos numeric,
  export_estado_embarque text,
  export_local_embarque text,
  obs_pedido text,
  info_cint text,
  info_imp_api text,
  info_dt_inc date,
  info_hr_inc text,
  info_user_inc text,
  info_dt_alt date,
  info_hr_alt text,
  info_user_alt text,
  synced_at timestamptz default now()
);

alter table omie_orders
  add column if not exists codigo_pedido_integracao text,
  add column if not exists numero_pedido text,
  add column if not exists codigo_cliente bigint,
  add column if not exists codigo_cenario bigint,
  add column if not exists codigo_local_estoque bigint,
  add column if not exists codigo_parcela text,
  add column if not exists data_previsao date,
  add column if not exists etapa text,
  add column if not exists qtde_itens numeric,
  add column if not exists origem_pedido text,
  add column if not exists pedido_status text,
  add column if not exists codigo_categoria text,
  add column if not exists codigo_conta_corrente bigint,
  add column if not exists codigo_departamento text,
  add column if not exists codigo_tipo_documento text,
  add column if not exists codigo_vendedor bigint,
  add column if not exists codigo_projeto bigint,
  add column if not exists consumidor_final text,
  add column if not exists enviar_email boolean,
  add column if not exists numero_pedido_cliente text,
  add column if not exists obs_venda text,
  add column if not exists obs_internas text,
  add column if not exists utilizar_emails text,
  add column if not exists codigo_transportadora bigint,
  add column if not exists modalidade_frete text,
  add column if not exists placa_veiculo text,
  add column if not exists qtde_volumes numeric,
  add column if not exists peso_bruto numeric,
  add column if not exists peso_liquido numeric,
  add column if not exists uf_veiculo text,
  add column if not exists valor_frete numeric,
  add column if not exists especie_volumes text,
  add column if not exists marca_volumes text,
  add column if not exists valor_mercadorias numeric,
  add column if not exists valor_total_pedido numeric,
  add column if not exists valor_descontos numeric,
  add column if not exists valor_acrescimos numeric,
  add column if not exists export_estado_embarque text,
  add column if not exists export_local_embarque text,
  add column if not exists obs_pedido text,
  add column if not exists info_cint text,
  add column if not exists info_imp_api text,
  add column if not exists info_dt_inc date,
  add column if not exists info_hr_inc text,
  add column if not exists info_user_inc text,
  add column if not exists info_dt_alt date,
  add column if not exists info_hr_alt text,
  add column if not exists info_user_alt text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_orders_synced on omie_orders (synced_at);

-- child of omie_orders: array `det`
create table if not exists omie_order_items (
  omie_id text not null,
  codigo_pedido bigint not null,
  codigo_item bigint,
  codigo_item_integracao text,
  simples_nacional text,
  codigo_produto bigint,
  codigo_produto_integ text,
  cfop text,
  cod_int_tab_preco text,
  codigo_tabela_preco bigint,
  descricao text,
  descricao_complementar text,
  ean text,
  ncm text,
  tipo_desconto text,
  unidade text,
  quantidade numeric,
  valor_unitario numeric,
  valor_deducao numeric,
  percentual_desconto numeric,
  valor_desconto numeric,
  valor_mercadoria numeric,
  valor_total numeric,
  reservado boolean,
  inventario_codigo_local_estoque bigint,
  inventario_motivo_baixa text,
  inventario_id_lote text,
  inventario_quantidade numeric,
  obs_item text,
  icms_base numeric,
  icms_valor numeric,
  icms_aliquota numeric,
  icms_cst text,
  icms_origem text,
  info_dt_inc date,
  info_hr_inc text,
  info_dt_alt date,
  info_hr_alt text,
  synced_at timestamptz default now(),
  primary key (codigo_pedido, omie_id)
);

alter table omie_order_items
  add column if not exists codigo_item bigint,
  add column if not exists codigo_item_integracao text,
  add column if not exists simples_nacional text,
  add column if not exists codigo_produto bigint,
  add column if not exists codigo_produto_integ text,
  add column if not exists cfop text,
  add column if not exists cod_int_tab_preco text,
  add column if not exists codigo_tabela_preco bigint,
  add column if not exists descricao text,
  add column if not exists descricao_complementar text,
  add column if not exists ean text,
  add column if not exists ncm text,
  add column if not exists tipo_desconto text,
  add column if not exists unidade text,
  add column if not exists quantidade numeric,
  add column if not exists valor_unitario numeric,
  add column if not exists valor_deducao numeric,
  add column if not exists percentual_desconto numeric,
  add column if not exists valor_desconto numeric,
  add column if not exists valor_mercadoria numeric,
  add column if not exists valor_total numeric,
  add column if not exists reservado boolean,
  add column if not exists inventario_codigo_local_estoque bigint,
  add column if not exists inventario_motivo_baixa text,
  add column if not exists inventario_id_lote text,
  add column if not exists inventario_quantidade numeric,
  add column if not exists obs_item text,
  add column if not exists icms_base numeric,
  add column if not exists icms_valor numeric,
  add column if not exists icms_aliquota numeric,
  add column if not exists icms_cst text,
  add column if not exists icms_origem text,
  add column if not exists info_dt_inc date,
  add column if not exists info_hr_inc text,
  add column if not exists info_dt_alt date,
  add column if not exists info_hr_alt text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_order_items_codigo_pedido on omie_order_items (codigo_pedido);
create index if not exists idx_omie_order_items_synced on omie_order_items (synced_at);

-- child of omie_orders: array `lista_parcelas.parcela`
create table if not exists omie_order_lancamentos (
  omie_id text not null,
  codigo_pedido bigint not null,
  numero_parcela bigint,
  codigo_lancamento bigint,
  data_vencimento date,
  valor numeric,
  percentual numeric,
  meio_pagamento text,
  quitado boolean,
  synced_at timestamptz default now(),
  primary key (codigo_pedido, omie_id)
);

alter table omie_order_lancamentos
  add column if not exists numero_parcela bigint,
  add column if not exists codigo_lancamento bigint,
  add column if not exists data_vencimento date,
  add column if not exists valor numeric,
  add column if not exists percentual numeric,
  add column if not exists meio_pagamento text,
  add column if not exists quitado boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_order_lancamentos_codigo_pedido on omie_order_lancamentos (codigo_pedido);
create index if not exists idx_omie_order_lancamentos_synced on omie_order_lancamentos (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_accounts_receivable  (phase 0 (legacy), tier critical)
-- Accounts receivable
-- Endpoint: financas/contareceber/ListarContasReceber
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_accounts_receivable (
  codigo_lancamento_omie bigint primary key,
  codigo_lancamento_integ text,
  codigo_cliente_fornecedor bigint,
  codigo_cliente_integ text,
  numero_documento text,
  numero_documento_fiscal text,
  numero_parcela text,
  data_emissao date,
  data_vencimento date,
  data_previsao date,
  data_pagamento date,
  data_registro date,
  valor_documento numeric,
  valor_recebido numeric,
  valor_pis numeric,
  valor_cofins numeric,
  valor_csll numeric,
  valor_ir numeric,
  valor_iss numeric,
  valor_inss numeric,
  percentual_juros numeric,
  data_juros date,
  codigo_categoria text,
  codigo_tipo_documento text,
  codigo_conta_corrente bigint,
  codigo_projeto bigint,
  codigo_vendedor bigint,
  codigo_departamento text,
  status_titulo text,
  operacao text,
  observacao text,
  codigo_barras text,
  numero_boleto text,
  codigo_barras_dac text,
  nosso_numero text,
  info_cint text,
  info_imp_api text,
  info_dt_inc date,
  info_hr_inc text,
  info_user_inc text,
  info_dt_alt date,
  info_hr_alt text,
  info_user_alt text,
  distribuicao_codigo text,
  distribuicao_valor numeric,
  distribuicao_percentual numeric,
  synced_at timestamptz default now()
);

alter table omie_accounts_receivable
  add column if not exists codigo_lancamento_integ text,
  add column if not exists codigo_cliente_fornecedor bigint,
  add column if not exists codigo_cliente_integ text,
  add column if not exists numero_documento text,
  add column if not exists numero_documento_fiscal text,
  add column if not exists numero_parcela text,
  add column if not exists data_emissao date,
  add column if not exists data_vencimento date,
  add column if not exists data_previsao date,
  add column if not exists data_pagamento date,
  add column if not exists data_registro date,
  add column if not exists valor_documento numeric,
  add column if not exists valor_recebido numeric,
  add column if not exists valor_pis numeric,
  add column if not exists valor_cofins numeric,
  add column if not exists valor_csll numeric,
  add column if not exists valor_ir numeric,
  add column if not exists valor_iss numeric,
  add column if not exists valor_inss numeric,
  add column if not exists percentual_juros numeric,
  add column if not exists data_juros date,
  add column if not exists codigo_categoria text,
  add column if not exists codigo_tipo_documento text,
  add column if not exists codigo_conta_corrente bigint,
  add column if not exists codigo_projeto bigint,
  add column if not exists codigo_vendedor bigint,
  add column if not exists codigo_departamento text,
  add column if not exists status_titulo text,
  add column if not exists operacao text,
  add column if not exists observacao text,
  add column if not exists codigo_barras text,
  add column if not exists numero_boleto text,
  add column if not exists codigo_barras_dac text,
  add column if not exists nosso_numero text,
  add column if not exists info_cint text,
  add column if not exists info_imp_api text,
  add column if not exists info_dt_inc date,
  add column if not exists info_hr_inc text,
  add column if not exists info_user_inc text,
  add column if not exists info_dt_alt date,
  add column if not exists info_hr_alt text,
  add column if not exists info_user_alt text,
  add column if not exists distribuicao_codigo text,
  add column if not exists distribuicao_valor numeric,
  add column if not exists distribuicao_percentual numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_accounts_receivable_synced on omie_accounts_receivable (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_accounts_payable  (phase 0 (legacy), tier critical)
-- Accounts payable
-- Endpoint: financas/contapagar/ListarContasPagar
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_accounts_payable (
  codigo_lancamento_omie bigint primary key,
  codigo_lancamento_integ text,
  codigo_cliente_fornecedor bigint,
  codigo_cliente_integ text,
  numero_documento text,
  numero_documento_fiscal text,
  numero_parcela text,
  data_emissao date,
  data_vencimento date,
  data_previsao date,
  data_pagamento date,
  data_registro date,
  valor_documento numeric,
  valor_pago numeric,
  valor_pis numeric,
  valor_cofins numeric,
  valor_csll numeric,
  valor_ir numeric,
  valor_iss numeric,
  valor_inss numeric,
  codigo_categoria text,
  codigo_tipo_documento text,
  codigo_conta_corrente bigint,
  codigo_projeto bigint,
  codigo_vendedor bigint,
  codigo_departamento text,
  status_titulo text,
  operacao text,
  observacao text,
  codigo_barras text,
  numero_boleto text,
  nosso_numero text,
  info_cint text,
  info_imp_api text,
  info_dt_inc date,
  info_hr_inc text,
  info_user_inc text,
  info_dt_alt date,
  info_hr_alt text,
  info_user_alt text,
  synced_at timestamptz default now()
);

alter table omie_accounts_payable
  add column if not exists codigo_lancamento_integ text,
  add column if not exists codigo_cliente_fornecedor bigint,
  add column if not exists codigo_cliente_integ text,
  add column if not exists numero_documento text,
  add column if not exists numero_documento_fiscal text,
  add column if not exists numero_parcela text,
  add column if not exists data_emissao date,
  add column if not exists data_vencimento date,
  add column if not exists data_previsao date,
  add column if not exists data_pagamento date,
  add column if not exists data_registro date,
  add column if not exists valor_documento numeric,
  add column if not exists valor_pago numeric,
  add column if not exists valor_pis numeric,
  add column if not exists valor_cofins numeric,
  add column if not exists valor_csll numeric,
  add column if not exists valor_ir numeric,
  add column if not exists valor_iss numeric,
  add column if not exists valor_inss numeric,
  add column if not exists codigo_categoria text,
  add column if not exists codigo_tipo_documento text,
  add column if not exists codigo_conta_corrente bigint,
  add column if not exists codigo_projeto bigint,
  add column if not exists codigo_vendedor bigint,
  add column if not exists codigo_departamento text,
  add column if not exists status_titulo text,
  add column if not exists operacao text,
  add column if not exists observacao text,
  add column if not exists codigo_barras text,
  add column if not exists numero_boleto text,
  add column if not exists nosso_numero text,
  add column if not exists info_cint text,
  add column if not exists info_imp_api text,
  add column if not exists info_dt_inc date,
  add column if not exists info_hr_inc text,
  add column if not exists info_user_inc text,
  add column if not exists info_dt_alt date,
  add column if not exists info_hr_alt text,
  add column if not exists info_user_alt text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_accounts_payable_synced on omie_accounts_payable (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_service_orders  (phase 0 (legacy), tier critical)
-- Service orders (OS)
-- Endpoint: servicos/os/ListarOS
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_service_orders (
  codigo_os bigint primary key,
  codigo_cliente bigint,
  numero_os text,
  codigo_parcela text,
  data_previsao date,
  data_faturamento date,
  etapa text,
  codigo_local_prest text,
  codigo_intermediador bigint,
  observacoes text,
  codigo_categoria text,
  codigo_departamento text,
  codigo_projeto bigint,
  codigo_conta_corrente bigint,
  codigo_vendedor bigint,
  codigo_natureza text,
  numero_pedido_cliente text,
  valor_total_servicos numeric,
  valor_total_pecas numeric,
  valor_outras_ret numeric,
  valor_total_outros numeric,
  valor_total_iss numeric,
  valor_total_pis numeric,
  valor_total_cofins numeric,
  valor_total_csll numeric,
  valor_total_ir numeric,
  valor_total_inss numeric,
  info_cint text,
  info_dt_inc date,
  info_hr_inc text,
  info_user_inc text,
  info_dt_alt date,
  info_hr_alt text,
  info_user_alt text,
  synced_at timestamptz default now()
);

alter table omie_service_orders
  add column if not exists codigo_cliente bigint,
  add column if not exists numero_os text,
  add column if not exists codigo_parcela text,
  add column if not exists data_previsao date,
  add column if not exists data_faturamento date,
  add column if not exists etapa text,
  add column if not exists codigo_local_prest text,
  add column if not exists codigo_intermediador bigint,
  add column if not exists observacoes text,
  add column if not exists codigo_categoria text,
  add column if not exists codigo_departamento text,
  add column if not exists codigo_projeto bigint,
  add column if not exists codigo_conta_corrente bigint,
  add column if not exists codigo_vendedor bigint,
  add column if not exists codigo_natureza text,
  add column if not exists numero_pedido_cliente text,
  add column if not exists valor_total_servicos numeric,
  add column if not exists valor_total_pecas numeric,
  add column if not exists valor_outras_ret numeric,
  add column if not exists valor_total_outros numeric,
  add column if not exists valor_total_iss numeric,
  add column if not exists valor_total_pis numeric,
  add column if not exists valor_total_cofins numeric,
  add column if not exists valor_total_csll numeric,
  add column if not exists valor_total_ir numeric,
  add column if not exists valor_total_inss numeric,
  add column if not exists info_cint text,
  add column if not exists info_dt_inc date,
  add column if not exists info_hr_inc text,
  add column if not exists info_user_inc text,
  add column if not exists info_dt_alt date,
  add column if not exists info_hr_alt text,
  add column if not exists info_user_alt text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_service_orders_synced on omie_service_orders (synced_at);

-- child of omie_service_orders: array `ServicosPrestados`
create table if not exists omie_service_order_items (
  omie_id text not null,
  codigo_os bigint not null,
  codigo_serv_mun text,
  codigo_lc116 text,
  descricao_servico text,
  quantidade numeric,
  valor_unitario numeric,
  valor_total numeric,
  cnae text,
  synced_at timestamptz default now(),
  primary key (codigo_os, omie_id)
);

alter table omie_service_order_items
  add column if not exists codigo_serv_mun text,
  add column if not exists codigo_lc116 text,
  add column if not exists descricao_servico text,
  add column if not exists quantidade numeric,
  add column if not exists valor_unitario numeric,
  add column if not exists valor_total numeric,
  add column if not exists cnae text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_service_order_items_codigo_os on omie_service_order_items (codigo_os);
create index if not exists idx_omie_service_order_items_synced on omie_service_order_items (synced_at);

-- child of omie_service_orders: array `Parcelas`
create table if not exists omie_service_order_parcels (
  omie_id text not null,
  codigo_os bigint not null,
  numero_parcela bigint,
  data_vencimento date,
  valor numeric,
  percentual numeric,
  synced_at timestamptz default now(),
  primary key (codigo_os, omie_id)
);

alter table omie_service_order_parcels
  add column if not exists numero_parcela bigint,
  add column if not exists data_vencimento date,
  add column if not exists valor numeric,
  add column if not exists percentual numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_service_order_parcels_codigo_os on omie_service_order_parcels (codigo_os);
create index if not exists idx_omie_service_order_parcels_synced on omie_service_order_parcels (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_products  (phase 0 (legacy), tier critical)
-- Products catalog
-- Endpoint: geral/produtos/ListarProdutos
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_products (
  codigo_produto bigint primary key,
  codigo_produto_integracao text,
  codigo text,
  descricao text,
  descricao_detalhada text,
  descricao_familia text,
  codigo_familia bigint,
  unidade text,
  ncm text,
  ean text,
  cest text,
  cfop text,
  origem_mercadoria text,
  csosn_icms text,
  cst_pis text,
  cst_cofins text,
  cst_ipi text,
  "tipoItem" text,
  marca text,
  modelo text,
  valor_unitario numeric,
  estoque_minimo numeric,
  aliquota_icms numeric,
  aliquota_ipi numeric,
  peso_bruto numeric,
  peso_liq numeric,
  altura numeric,
  largura numeric,
  profundidade numeric,
  dias_garantia numeric,
  dias_crossdocking numeric,
  tipo_estoque text,
  obs_internas text,
  bloqueado boolean,
  bloquear_exclusao boolean,
  inativo boolean,
  ativo boolean,
  imagem_principal text,
  info_dt_inc date,
  info_hr_inc text,
  info_user_inc text,
  info_dt_alt date,
  info_hr_alt text,
  info_user_alt text,
  synced_at timestamptz default now()
);

alter table omie_products
  add column if not exists codigo_produto_integracao text,
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists descricao_detalhada text,
  add column if not exists descricao_familia text,
  add column if not exists codigo_familia bigint,
  add column if not exists unidade text,
  add column if not exists ncm text,
  add column if not exists ean text,
  add column if not exists cest text,
  add column if not exists cfop text,
  add column if not exists origem_mercadoria text,
  add column if not exists csosn_icms text,
  add column if not exists cst_pis text,
  add column if not exists cst_cofins text,
  add column if not exists cst_ipi text,
  add column if not exists "tipoItem" text,
  add column if not exists marca text,
  add column if not exists modelo text,
  add column if not exists valor_unitario numeric,
  add column if not exists estoque_minimo numeric,
  add column if not exists aliquota_icms numeric,
  add column if not exists aliquota_ipi numeric,
  add column if not exists peso_bruto numeric,
  add column if not exists peso_liq numeric,
  add column if not exists altura numeric,
  add column if not exists largura numeric,
  add column if not exists profundidade numeric,
  add column if not exists dias_garantia numeric,
  add column if not exists dias_crossdocking numeric,
  add column if not exists tipo_estoque text,
  add column if not exists obs_internas text,
  add column if not exists bloqueado boolean,
  add column if not exists bloquear_exclusao boolean,
  add column if not exists inativo boolean,
  add column if not exists ativo boolean,
  add column if not exists imagem_principal text,
  add column if not exists info_dt_inc date,
  add column if not exists info_hr_inc text,
  add column if not exists info_user_inc text,
  add column if not exists info_dt_alt date,
  add column if not exists info_hr_alt text,
  add column if not exists info_user_alt text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_products_synced on omie_products (synced_at);

-- child of omie_products: array `caracteristicas`
create table if not exists omie_product_caract_values (
  omie_id text not null,
  codigo_produto bigint not null,
  codigo_caracteristica text,
  nome_caracteristica text,
  conteudo text,
  synced_at timestamptz default now(),
  primary key (codigo_produto, omie_id)
);

alter table omie_product_caract_values
  add column if not exists codigo_caracteristica text,
  add column if not exists nome_caracteristica text,
  add column if not exists conteudo text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_product_caract_values_codigo_produto on omie_product_caract_values (codigo_produto);
create index if not exists idx_omie_product_caract_values_synced on omie_product_caract_values (synced_at);

-- child of omie_products: array `tags`
create table if not exists omie_product_tags (
  omie_id text not null,
  codigo_produto bigint not null,
  tag text,
  synced_at timestamptz default now(),
  primary key (codigo_produto, omie_id)
);

alter table omie_product_tags
  add column if not exists tag text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_product_tags_codigo_produto on omie_product_tags (codigo_produto);
create index if not exists idx_omie_product_tags_synced on omie_product_tags (synced_at);

-- child of omie_products: array `imagens`
create table if not exists omie_product_images (
  omie_id text not null,
  codigo_produto bigint not null,
  url_imagem text,
  synced_at timestamptz default now(),
  primary key (codigo_produto, omie_id)
);

alter table omie_product_images
  add column if not exists url_imagem text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_product_images_codigo_produto on omie_product_images (codigo_produto);
create index if not exists idx_omie_product_images_synced on omie_product_images (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_crm_opportunities  (phase 0 (legacy), tier critical)
-- CRM opportunities (pipeline)
-- Endpoint: crm/oportunidades/ListarOportunidades
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_crm_opportunities (
  cod_oportunidade bigint primary key,
  descricao text,
  codigo_conta bigint,
  codigo_contato bigint,
  codigo_vendedor bigint,
  codigo_origem bigint,
  codigo_solucao bigint,
  observacoes_descricao text,
  codigo_status bigint,
  codigo_fase bigint,
  codigo_motivo_perda bigint,
  ticket numeric,
  previsao_mes numeric,
  previsao_ano numeric,
  data_inclusao date,
  hora_inclusao text,
  data_alteracao date,
  hora_alteracao text,
  synced_at timestamptz default now()
);

alter table omie_crm_opportunities
  add column if not exists descricao text,
  add column if not exists codigo_conta bigint,
  add column if not exists codigo_contato bigint,
  add column if not exists codigo_vendedor bigint,
  add column if not exists codigo_origem bigint,
  add column if not exists codigo_solucao bigint,
  add column if not exists observacoes_descricao text,
  add column if not exists codigo_status bigint,
  add column if not exists codigo_fase bigint,
  add column if not exists codigo_motivo_perda bigint,
  add column if not exists ticket numeric,
  add column if not exists previsao_mes numeric,
  add column if not exists previsao_ano numeric,
  add column if not exists data_inclusao date,
  add column if not exists hora_inclusao text,
  add column if not exists data_alteracao date,
  add column if not exists hora_alteracao text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_crm_opportunities_synced on omie_crm_opportunities (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_crm_activities  (phase 0 (legacy), tier critical)
-- CRM activities / tasks
-- Endpoint: crm/tarefas/ListarTarefas
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_crm_activities (
  cod_tarefa bigint primary key,
  cod_oportunidade bigint,
  cod_atividade bigint,
  cod_usuario bigint,
  data date,
  hora text,
  descricao text,
  realizada boolean,
  em_execucao boolean,
  synced_at timestamptz default now()
);

alter table omie_crm_activities
  add column if not exists cod_oportunidade bigint,
  add column if not exists cod_atividade bigint,
  add column if not exists cod_usuario bigint,
  add column if not exists data date,
  add column if not exists hora text,
  add column if not exists descricao text,
  add column if not exists realizada boolean,
  add column if not exists em_execucao boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_crm_activities_synced on omie_crm_activities (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_categories  (phase 1, tier critical)
-- Operational chart of accounts
-- Endpoint: geral/categorias/ListarCategorias
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_categories (
  omie_id text primary key,
  codigo text,
  descricao text,
  descricao_padrao text,
  natureza text,
  tipo_categoria text,
  codigo_dre text,
  conta_despesa boolean,
  conta_receita boolean,
  totalizadora boolean,
  transferencia boolean,
  nao_exibir boolean,
  inativa boolean,
  definida_usuario boolean,
  id_conta_contabil text,
  codigo_centro_receita_despesa text,
  synced_at timestamptz default now()
);

alter table omie_categories
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists descricao_padrao text,
  add column if not exists natureza text,
  add column if not exists tipo_categoria text,
  add column if not exists codigo_dre text,
  add column if not exists conta_despesa boolean,
  add column if not exists conta_receita boolean,
  add column if not exists totalizadora boolean,
  add column if not exists transferencia boolean,
  add column if not exists nao_exibir boolean,
  add column if not exists inativa boolean,
  add column if not exists definida_usuario boolean,
  add column if not exists id_conta_contabil text,
  add column if not exists codigo_centro_receita_despesa text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_categories_synced on omie_categories (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_departments  (phase 1, tier critical)
-- Cost centers / departments
-- Endpoint: geral/departamentos/ListarDepartamentos
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_departments (
  omie_id text primary key,
  codigo text,
  descricao text,
  estrutura text,
  inativo boolean,
  synced_at timestamptz default now()
);

alter table omie_departments
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists estrutura text,
  add column if not exists inativo boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_departments_synced on omie_departments (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_projects  (phase 1, tier critical)
-- Cost sharing / projects
-- Endpoint: geral/projetos/ListarProjetos
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_projects (
  omie_id text primary key,
  codigo text,
  codint text,
  nome text,
  inativo boolean,
  synced_at timestamptz default now()
);

alter table omie_projects
  add column if not exists codigo text,
  add column if not exists codint text,
  add column if not exists nome text,
  add column if not exists inativo boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_projects_synced on omie_projects (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_document_types  (phase 1, tier critical)
-- Document types (NF, BOL, DUP…)
-- Endpoint: geral/tiposdoc/PesquisarTipoDocumento
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_document_types (
  omie_id text primary key,
  codigo text,
  descricao text,
  synced_at timestamptz default now()
);

alter table omie_document_types
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_document_types_synced on omie_document_types (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_units  (phase 1, tier critical)
-- Units of measure (UN, KG, CX…)
-- Endpoint: geral/unidade/ListarUnidades
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_units (
  omie_id text primary key,
  codigo text,
  descricao text,
  synced_at timestamptz default now()
);

alter table omie_units
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_units_synced on omie_units (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_familias_produtos  (phase 1, tier critical)
-- Product families / grouping
-- Endpoint: geral/familias/PesquisarFamilias
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_familias_produtos (
  omie_id text primary key,
  codigo text,
  codigo_familia_integracao text,
  descricao text,
  inteiro_familia bigint,
  inativa boolean,
  synced_at timestamptz default now()
);

alter table omie_familias_produtos
  add column if not exists codigo text,
  add column if not exists codigo_familia_integracao text,
  add column if not exists descricao text,
  add column if not exists inteiro_familia bigint,
  add column if not exists inativa boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_familias_produtos_synced on omie_familias_produtos (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_billing_stages  (phase 1, tier critical)
-- Billing stages
-- Endpoint: produtos/etapafat/ListarEtapasFaturamento
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_billing_stages (
  omie_id text primary key,
  codigo text,
  descricao text,
  descricao_padrao text,
  inativo boolean,
  synced_at timestamptz default now()
);

alter table omie_billing_stages
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists descricao_padrao text,
  add column if not exists inativo boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_billing_stages_synced on omie_billing_stages (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_vendedores  (phase 1, tier critical)
-- Sales team
-- Endpoint: geral/vendedores/ListarVendedores
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_vendedores (
  omie_id text primary key,
  codigo bigint,
  codigo_integracao text,
  nome text,
  email text,
  fone text,
  cpf text,
  inativo boolean,
  synced_at timestamptz default now()
);

alter table omie_vendedores
  add column if not exists codigo bigint,
  add column if not exists codigo_integracao text,
  add column if not exists nome text,
  add column if not exists email text,
  add column if not exists fone text,
  add column if not exists cpf text,
  add column if not exists inativo boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_vendedores_synced on omie_vendedores (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_stock_locations  (phase 1, tier optional)
-- Warehouses / stock locations
-- Endpoint: estoque/local/ListarLocaisEstoque
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_stock_locations (
  omie_id text primary key,
  codigo_local_estoque bigint,
  codigo text,
  descricao text,
  tipo text,
  padrao boolean,
  inativo boolean,
  codigo_cliente bigint,
  disp_venda boolean,
  synced_at timestamptz default now()
);

alter table omie_stock_locations
  add column if not exists codigo_local_estoque bigint,
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists tipo text,
  add column if not exists padrao boolean,
  add column if not exists inativo boolean,
  add column if not exists codigo_cliente bigint,
  add column if not exists disp_venda boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_stock_locations_synced on omie_stock_locations (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_banks  (phase 1, tier important)
-- Bank lookup
-- Endpoint: geral/bancos/ListarBancos
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_banks (
  omie_id text primary key,
  codigo text,
  nome text,
  tipo text,
  synced_at timestamptz default now()
);

alter table omie_banks
  add column if not exists codigo text,
  add column if not exists nome text,
  add column if not exists tipo text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_banks_synced on omie_banks (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_parcelas  (phase 1, tier important)
-- Default payment conditions
-- Endpoint: geral/parcelas/ListarParcelas
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_parcelas (
  omie_id text primary key,
  codigo text,
  descricao text,
  dias numeric,
  percentual numeric,
  synced_at timestamptz default now()
);

alter table omie_parcelas
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists dias numeric,
  add column if not exists percentual numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_parcelas_synced on omie_parcelas (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_price_tables  (phase 1, tier optional)
-- Differentiated pricing
-- Endpoint: produtos/tabelaprecos/ListarTabelasPreco
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_price_tables (
  omie_id text primary key,
  cod_tab_preco bigint,
  cod_int_tab_preco text,
  nome text,
  dt_ini date,
  dt_fim date,
  ativo boolean,
  synced_at timestamptz default now()
);

alter table omie_price_tables
  add column if not exists cod_tab_preco bigint,
  add column if not exists cod_int_tab_preco text,
  add column if not exists nome text,
  add column if not exists dt_ini date,
  add column if not exists dt_fim date,
  add column if not exists ativo boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_price_tables_synced on omie_price_tables (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_crm_phases  (phase 1, tier important)
-- CRM opportunity phases
-- Endpoint: crm/fases/ListarFases
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_crm_phases (
  omie_id text primary key,
  cod_fase bigint,
  nome text,
  synced_at timestamptz default now()
);

alter table omie_crm_phases
  add column if not exists cod_fase bigint,
  add column if not exists nome text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_crm_phases_synced on omie_crm_phases (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_crm_status  (phase 1, tier important)
-- CRM opportunity statuses
-- Endpoint: crm/status/ListarStatus
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_crm_status (
  omie_id text primary key,
  cod_status bigint,
  nome text,
  synced_at timestamptz default now()
);

alter table omie_crm_status
  add column if not exists cod_status bigint,
  add column if not exists nome text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_crm_status_synced on omie_crm_status (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_crm_origens  (phase 1, tier important)
-- Acquisition channels
-- Endpoint: crm/origens/ListarOrigens
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_crm_origens (
  omie_id text primary key,
  cod_origem bigint,
  nome text,
  synced_at timestamptz default now()
);

alter table omie_crm_origens
  add column if not exists cod_origem bigint,
  add column if not exists nome text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_crm_origens_synced on omie_crm_origens (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_current_accounts  (phase 2, tier critical)
-- Bank current accounts / cards
-- Endpoint: geral/contacorrente/ListarContasCorrentes
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_current_accounts (
  omie_id text primary key,
  cod_cc bigint,
  cod_cc_int text,
  descricao text,
  codigo_banco text,
  codigo_agencia text,
  conta_corrente text,
  tipo text,
  saldo_inicial numeric,
  saldo_data date,
  valor_limite numeric,
  cnpj text,
  doc_titular text,
  nome_titular text,
  observacao text,
  codigo_categoria text,
  tipo_titular text,
  inativo boolean,
  synced_at timestamptz default now()
);

alter table omie_current_accounts
  add column if not exists cod_cc bigint,
  add column if not exists cod_cc_int text,
  add column if not exists descricao text,
  add column if not exists codigo_banco text,
  add column if not exists codigo_agencia text,
  add column if not exists conta_corrente text,
  add column if not exists tipo text,
  add column if not exists saldo_inicial numeric,
  add column if not exists saldo_data date,
  add column if not exists valor_limite numeric,
  add column if not exists cnpj text,
  add column if not exists doc_titular text,
  add column if not exists nome_titular text,
  add column if not exists observacao text,
  add column if not exists codigo_categoria text,
  add column if not exists tipo_titular text,
  add column if not exists inativo boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_current_accounts_synced on omie_current_accounts (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_financial_movements  (phase 2, tier critical)
-- Cash flow / financial movements
-- Endpoint: financas/mf/ListarMovimentos
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_financial_movements (
  omie_id text primary key,
  cod_titulo bigint,
  cod_int_titulo text,
  num_titulo text,
  natureza text,
  tipo text,
  status text,
  origem text,
  operacao text,
  cod_cliente bigint,
  cpf_cnpj_cliente text,
  cod_categoria text,
  cod_cc bigint,
  dt_emissao date,
  dt_vencimento date,
  dt_previsao date,
  dt_pagamento date,
  dt_registro date,
  dt_credito date,
  dt_conciliacao date,
  cod_origem bigint,
  cod_projeto bigint,
  cod_pedido bigint,
  cod_os bigint,
  cod_titulo_repet bigint,
  valor_titulo numeric,
  percent_juros numeric,
  percent_multa numeric,
  percent_desconto numeric,
  valor_pis numeric,
  valor_cofins numeric,
  valor_csll numeric,
  valor_ir numeric,
  valor_iss numeric,
  valor_inss numeric,
  num_doc_fiscal text,
  numero_parcela text,
  observacao text,
  cod_vendedor bigint,
  liquidado boolean,
  val_pago numeric,
  val_aberto numeric,
  val_liquido numeric,
  val_juros numeric,
  val_multa numeric,
  val_desconto numeric,
  codigo_barras text,
  numero_boleto text,
  nosso_numero text,
  url_boleto text,
  cod_departamento text,
  percentual_departamento numeric,
  synced_at timestamptz default now()
);

alter table omie_financial_movements
  add column if not exists cod_titulo bigint,
  add column if not exists cod_int_titulo text,
  add column if not exists num_titulo text,
  add column if not exists natureza text,
  add column if not exists tipo text,
  add column if not exists status text,
  add column if not exists origem text,
  add column if not exists operacao text,
  add column if not exists cod_cliente bigint,
  add column if not exists cpf_cnpj_cliente text,
  add column if not exists cod_categoria text,
  add column if not exists cod_cc bigint,
  add column if not exists dt_emissao date,
  add column if not exists dt_vencimento date,
  add column if not exists dt_previsao date,
  add column if not exists dt_pagamento date,
  add column if not exists dt_registro date,
  add column if not exists dt_credito date,
  add column if not exists dt_conciliacao date,
  add column if not exists cod_origem bigint,
  add column if not exists cod_projeto bigint,
  add column if not exists cod_pedido bigint,
  add column if not exists cod_os bigint,
  add column if not exists cod_titulo_repet bigint,
  add column if not exists valor_titulo numeric,
  add column if not exists percent_juros numeric,
  add column if not exists percent_multa numeric,
  add column if not exists percent_desconto numeric,
  add column if not exists valor_pis numeric,
  add column if not exists valor_cofins numeric,
  add column if not exists valor_csll numeric,
  add column if not exists valor_ir numeric,
  add column if not exists valor_iss numeric,
  add column if not exists valor_inss numeric,
  add column if not exists num_doc_fiscal text,
  add column if not exists numero_parcela text,
  add column if not exists observacao text,
  add column if not exists cod_vendedor bigint,
  add column if not exists liquidado boolean,
  add column if not exists val_pago numeric,
  add column if not exists val_aberto numeric,
  add column if not exists val_liquido numeric,
  add column if not exists val_juros numeric,
  add column if not exists val_multa numeric,
  add column if not exists val_desconto numeric,
  add column if not exists codigo_barras text,
  add column if not exists numero_boleto text,
  add column if not exists nosso_numero text,
  add column if not exists url_boleto text,
  add column if not exists cod_departamento text,
  add column if not exists percentual_departamento numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_financial_movements_synced on omie_financial_movements (synced_at);

-- child of omie_financial_movements: array `detalhes.aListaCateg`
create table if not exists omie_financial_movements_categorias (
  omie_id text not null,
  parent_omie_id text not null,
  cod_categoria text,
  valor numeric,
  percentual numeric,
  cod_distribuicao bigint,
  synced_at timestamptz default now(),
  primary key (parent_omie_id, omie_id)
);

alter table omie_financial_movements_categorias
  add column if not exists cod_categoria text,
  add column if not exists valor numeric,
  add column if not exists percentual numeric,
  add column if not exists cod_distribuicao bigint,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_financial_movements_categorias_parent_omie_id on omie_financial_movements_categorias (parent_omie_id);
create index if not exists idx_omie_financial_movements_categorias_synced on omie_financial_movements_categorias (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_current_account_transactions  (phase 2, tier important)
-- Bank transaction details
-- Endpoint: financas/contacorrentelancamentos/ListarLancCC
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_current_account_transactions (
  omie_id text primary key,
  cod_lanc bigint,
  cod_int_lanc text,
  cod_agrup bigint,
  cod_cc bigint,
  dt_lanc date,
  dt_emissao date,
  valor_lanc numeric,
  cod_categoria text,
  tipo text,
  num_doc text,
  cod_cliente bigint,
  cod_projeto bigint,
  cod_departamento text,
  cod_titulo bigint,
  observacao text,
  origem text,
  natureza text,
  dt_conciliacao date,
  synced_at timestamptz default now()
);

alter table omie_current_account_transactions
  add column if not exists cod_lanc bigint,
  add column if not exists cod_int_lanc text,
  add column if not exists cod_agrup bigint,
  add column if not exists cod_cc bigint,
  add column if not exists dt_lanc date,
  add column if not exists dt_emissao date,
  add column if not exists valor_lanc numeric,
  add column if not exists cod_categoria text,
  add column if not exists tipo text,
  add column if not exists num_doc text,
  add column if not exists cod_cliente bigint,
  add column if not exists cod_projeto bigint,
  add column if not exists cod_departamento text,
  add column if not exists cod_titulo bigint,
  add column if not exists observacao text,
  add column if not exists origem text,
  add column if not exists natureza text,
  add column if not exists dt_conciliacao date,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_current_account_transactions_synced on omie_current_account_transactions (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_estoque_posicao  (phase 3, tier optional)
-- Current stock balance
-- Endpoint: estoque/consulta/ListarPosEstoque
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_estoque_posicao (
  omie_id text primary key,
  cod_prod bigint,
  cod_int text,
  codigo text,
  descricao text,
  ean text,
  unidade text,
  preco_unitario numeric,
  saldo numeric,
  cmc numeric,
  pendente numeric,
  estoque_minimo numeric,
  codigo_local_estoque bigint,
  reservado numeric,
  fisico numeric,
  synced_at timestamptz default now()
);

alter table omie_estoque_posicao
  add column if not exists cod_prod bigint,
  add column if not exists cod_int text,
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists ean text,
  add column if not exists unidade text,
  add column if not exists preco_unitario numeric,
  add column if not exists saldo numeric,
  add column if not exists cmc numeric,
  add column if not exists pendente numeric,
  add column if not exists estoque_minimo numeric,
  add column if not exists codigo_local_estoque bigint,
  add column if not exists reservado numeric,
  add column if not exists fisico numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_estoque_posicao_synced on omie_estoque_posicao (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_estoque_movimentos  (phase 3, tier optional)
-- Stock movement history (parent: product summary)
-- Endpoint: estoque/movestoque/ListarMovimentos
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_estoque_movimentos (
  omie_id text primary key,
  cod_prod bigint,
  cod_int_prod text,
  codigo text,
  descricao text,
  synced_at timestamptz default now()
);

alter table omie_estoque_movimentos
  add column if not exists cod_prod bigint,
  add column if not exists cod_int_prod text,
  add column if not exists codigo text,
  add column if not exists descricao text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_estoque_movimentos_synced on omie_estoque_movimentos (synced_at);

-- child of omie_estoque_movimentos: array `movimentos`
create table if not exists omie_estoque_movimentos_lancamentos (
  omie_id text not null,
  parent_omie_id text not null,
  id_mov_est bigint,
  cod_mov bigint,
  codigo_local bigint,
  dt_movimento date,
  tipo_movimento text,
  origem text,
  numero_documento text,
  observacao text,
  quantidade numeric,
  valor_unitario numeric,
  valor_total numeric,
  saldo_inicial numeric,
  saldo_final numeric,
  cmc_inicial numeric,
  cmc_final numeric,
  id_pedido bigint,
  id_lote bigint,
  id_ajuste bigint,
  synced_at timestamptz default now(),
  primary key (parent_omie_id, omie_id)
);

alter table omie_estoque_movimentos_lancamentos
  add column if not exists id_mov_est bigint,
  add column if not exists cod_mov bigint,
  add column if not exists codigo_local bigint,
  add column if not exists dt_movimento date,
  add column if not exists tipo_movimento text,
  add column if not exists origem text,
  add column if not exists numero_documento text,
  add column if not exists observacao text,
  add column if not exists quantidade numeric,
  add column if not exists valor_unitario numeric,
  add column if not exists valor_total numeric,
  add column if not exists saldo_inicial numeric,
  add column if not exists saldo_final numeric,
  add column if not exists cmc_inicial numeric,
  add column if not exists cmc_final numeric,
  add column if not exists id_pedido bigint,
  add column if not exists id_lote bigint,
  add column if not exists id_ajuste bigint,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_estoque_movimentos_lancamentos_parent_omie_id on omie_estoque_movimentos_lancamentos (parent_omie_id);
create index if not exists idx_omie_estoque_movimentos_lancamentos_synced on omie_estoque_movimentos_lancamentos (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_orders_purchase  (phase 4, tier optional)
-- Purchase orders (in flight)
-- Endpoint: produtos/pedidocompra/PesquisarPedCompra
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_orders_purchase (
  omie_id text primary key,
  cod_pedido bigint,
  numero_pedido text,
  cod_fornecedor bigint,
  cod_comprador bigint,
  dt_emissao date,
  dt_previsao date,
  valor_total numeric,
  valor_mercadorias numeric,
  valor_frete numeric,
  valor_desconto numeric,
  status text,
  observacoes text,
  synced_at timestamptz default now()
);

alter table omie_orders_purchase
  add column if not exists cod_pedido bigint,
  add column if not exists numero_pedido text,
  add column if not exists cod_fornecedor bigint,
  add column if not exists cod_comprador bigint,
  add column if not exists dt_emissao date,
  add column if not exists dt_previsao date,
  add column if not exists valor_total numeric,
  add column if not exists valor_mercadorias numeric,
  add column if not exists valor_frete numeric,
  add column if not exists valor_desconto numeric,
  add column if not exists status text,
  add column if not exists observacoes text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_orders_purchase_synced on omie_orders_purchase (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_notas_entrada  (phase 4, tier optional)
-- Inbound invoices (physical receipt)
-- Endpoint: produtos/notaentrada/ListarNotaEnt
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_notas_entrada (
  omie_id text primary key,
  id_nf bigint,
  id_nf_ent bigint,
  num_doc text,
  serie text,
  modelo text,
  dt_emissao date,
  dt_entrada date,
  cnpj_cpf text,
  razao_social text,
  valor_nota numeric,
  valor_total numeric,
  valor_desconto numeric,
  cfop text,
  tipo_operacao text,
  observacoes text,
  synced_at timestamptz default now()
);

alter table omie_notas_entrada
  add column if not exists id_nf bigint,
  add column if not exists id_nf_ent bigint,
  add column if not exists num_doc text,
  add column if not exists serie text,
  add column if not exists modelo text,
  add column if not exists dt_emissao date,
  add column if not exists dt_entrada date,
  add column if not exists cnpj_cpf text,
  add column if not exists razao_social text,
  add column if not exists valor_nota numeric,
  add column if not exists valor_total numeric,
  add column if not exists valor_desconto numeric,
  add column if not exists cfop text,
  add column if not exists tipo_operacao text,
  add column if not exists observacoes text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_notas_entrada_synced on omie_notas_entrada (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_nfe  (phase 5, tier optional)
-- Issued NF-e
-- Endpoint: produtos/nfconsultar/ListarNF
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_nfe (
  omie_id text primary key,
  id_nf bigint,
  cod_nf bigint,
  numero_nf text,
  serie text,
  modelo text,
  tipo_nf text,
  tipo_ambiente text,
  chave_nfe text,
  natureza_operacao text,
  dt_emissao date,
  dt_saida date,
  finalidade text,
  consumidor_final text,
  indicador_presenca text,
  cod_cliente bigint,
  cnpj_cpf text,
  razao_social text,
  email_dest text,
  endereco_dest text,
  numero_dest text,
  complemento_dest text,
  bairro_dest text,
  municipio_dest text,
  cmun_dest text,
  uf_dest text,
  cep_dest text,
  valor_bc_icms numeric,
  valor_icms numeric,
  valor_bc_icms_st numeric,
  valor_st numeric,
  valor_prod numeric,
  valor_frete numeric,
  valor_seguro numeric,
  valor_desconto numeric,
  valor_outras numeric,
  valor_ipi numeric,
  valor_pis numeric,
  valor_cofins numeric,
  valor_nota numeric,
  modalidade_frete text,
  cnpj_transportadora text,
  razao_transportadora text,
  ie_transportadora text,
  cnpj_emit text,
  inf_complementar text,
  inf_adic_fisco text,
  synced_at timestamptz default now()
);

alter table omie_nfe
  add column if not exists id_nf bigint,
  add column if not exists cod_nf bigint,
  add column if not exists numero_nf text,
  add column if not exists serie text,
  add column if not exists modelo text,
  add column if not exists tipo_nf text,
  add column if not exists tipo_ambiente text,
  add column if not exists chave_nfe text,
  add column if not exists natureza_operacao text,
  add column if not exists dt_emissao date,
  add column if not exists dt_saida date,
  add column if not exists finalidade text,
  add column if not exists consumidor_final text,
  add column if not exists indicador_presenca text,
  add column if not exists cod_cliente bigint,
  add column if not exists cnpj_cpf text,
  add column if not exists razao_social text,
  add column if not exists email_dest text,
  add column if not exists endereco_dest text,
  add column if not exists numero_dest text,
  add column if not exists complemento_dest text,
  add column if not exists bairro_dest text,
  add column if not exists municipio_dest text,
  add column if not exists cmun_dest text,
  add column if not exists uf_dest text,
  add column if not exists cep_dest text,
  add column if not exists valor_bc_icms numeric,
  add column if not exists valor_icms numeric,
  add column if not exists valor_bc_icms_st numeric,
  add column if not exists valor_st numeric,
  add column if not exists valor_prod numeric,
  add column if not exists valor_frete numeric,
  add column if not exists valor_seguro numeric,
  add column if not exists valor_desconto numeric,
  add column if not exists valor_outras numeric,
  add column if not exists valor_ipi numeric,
  add column if not exists valor_pis numeric,
  add column if not exists valor_cofins numeric,
  add column if not exists valor_nota numeric,
  add column if not exists modalidade_frete text,
  add column if not exists cnpj_transportadora text,
  add column if not exists razao_transportadora text,
  add column if not exists ie_transportadora text,
  add column if not exists cnpj_emit text,
  add column if not exists inf_complementar text,
  add column if not exists inf_adic_fisco text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_nfe_synced on omie_nfe (synced_at);

-- child of omie_nfe: array `det`
create table if not exists omie_nfe_items (
  omie_id text not null,
  parent_omie_id text not null,
  n_item bigint,
  cprod text,
  cean text,
  descricao text,
  ncm text,
  cest text,
  cfop text,
  unidade_comercial text,
  quantidade_comercial numeric,
  valor_unitario numeric,
  valor_produto numeric,
  unidade_tributada text,
  quantidade_tributada numeric,
  valor_unit_tributado numeric,
  valor_desconto numeric,
  valor_frete numeric,
  valor_seguro numeric,
  valor_outras numeric,
  icms_cst text,
  icms_origem text,
  icms_vbc numeric,
  icms_pbc numeric,
  icms_valor numeric,
  ipi_cst text,
  ipi_valor numeric,
  pis_cst text,
  pis_valor numeric,
  cofins_cst text,
  cofins_valor numeric,
  synced_at timestamptz default now(),
  primary key (parent_omie_id, omie_id)
);

alter table omie_nfe_items
  add column if not exists n_item bigint,
  add column if not exists cprod text,
  add column if not exists cean text,
  add column if not exists descricao text,
  add column if not exists ncm text,
  add column if not exists cest text,
  add column if not exists cfop text,
  add column if not exists unidade_comercial text,
  add column if not exists quantidade_comercial numeric,
  add column if not exists valor_unitario numeric,
  add column if not exists valor_produto numeric,
  add column if not exists unidade_tributada text,
  add column if not exists quantidade_tributada numeric,
  add column if not exists valor_unit_tributado numeric,
  add column if not exists valor_desconto numeric,
  add column if not exists valor_frete numeric,
  add column if not exists valor_seguro numeric,
  add column if not exists valor_outras numeric,
  add column if not exists icms_cst text,
  add column if not exists icms_origem text,
  add column if not exists icms_vbc numeric,
  add column if not exists icms_pbc numeric,
  add column if not exists icms_valor numeric,
  add column if not exists ipi_cst text,
  add column if not exists ipi_valor numeric,
  add column if not exists pis_cst text,
  add column if not exists pis_valor numeric,
  add column if not exists cofins_cst text,
  add column if not exists cofins_valor numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_nfe_items_parent_omie_id on omie_nfe_items (parent_omie_id);
create index if not exists idx_omie_nfe_items_synced on omie_nfe_items (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_crm_contatos  (phase 6, tier optional)
-- People in CRM accounts
-- Endpoint: crm/contatos/ListarContatos
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_crm_contatos (
  omie_id text primary key,
  cod bigint,
  cod_int text,
  nome text,
  sobrenome text,
  cargo text,
  email text,
  fone text,
  cod_conta bigint,
  cpf text,
  inativo boolean,
  synced_at timestamptz default now()
);

alter table omie_crm_contatos
  add column if not exists cod bigint,
  add column if not exists cod_int text,
  add column if not exists nome text,
  add column if not exists sobrenome text,
  add column if not exists cargo text,
  add column if not exists email text,
  add column if not exists fone text,
  add column if not exists cod_conta bigint,
  add column if not exists cpf text,
  add column if not exists inativo boolean,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_crm_contatos_synced on omie_crm_contatos (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_products_variation  (phase 7, tier industry)
-- Retail SKU variations (color, size)
-- Endpoint: geral/produtocaract/ListarVariacoes
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_products_variation (
  omie_id text primary key,
  cod_variacao bigint,
  cod_produto bigint,
  descricao text,
  codigo text,
  synced_at timestamptz default now()
);

alter table omie_products_variation
  add column if not exists cod_variacao bigint,
  add column if not exists cod_produto bigint,
  add column if not exists descricao text,
  add column if not exists codigo text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_products_variation_synced on omie_products_variation (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_products_kit  (phase 7, tier industry)
-- Combos / baskets
-- Endpoint: geral/produtoskit/ListarKits
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_products_kit (
  omie_id text primary key,
  codigo text,
  codigo_produto bigint,
  descricao text,
  synced_at timestamptz default now()
);

alter table omie_products_kit
  add column if not exists codigo text,
  add column if not exists codigo_produto bigint,
  add column if not exists descricao text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_products_kit_synced on omie_products_kit (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_products_lot  (phase 7, tier industry)
-- Regulated industry traceability
-- Endpoint: estoque/lote/ListarLotes
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_products_lot (
  omie_id text primary key,
  id_lote bigint,
  cod_prod bigint,
  descricao text,
  numero_lote text,
  data_validade date,
  quantidade numeric,
  synced_at timestamptz default now()
);

alter table omie_products_lot
  add column if not exists id_lote bigint,
  add column if not exists cod_prod bigint,
  add column if not exists descricao text,
  add column if not exists numero_lote text,
  add column if not exists data_validade date,
  add column if not exists quantidade numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_products_lot_synced on omie_products_lot (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_products_structure  (phase 7, tier industry)
-- Industrial BOM
-- Endpoint: geral/produtoestrutura/ListarEstruturas
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_products_structure (
  omie_id text primary key,
  id_estrutura bigint,
  cod_prod bigint,
  descricao text,
  synced_at timestamptz default now()
);

alter table omie_products_structure
  add column if not exists id_estrutura bigint,
  add column if not exists cod_prod bigint,
  add column if not exists descricao text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_products_structure_synced on omie_products_structure (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_orders_production  (phase 7, tier industry)
-- Manufacturing orders
-- Endpoint: producao/op/ListarOPs
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_orders_production (
  omie_id text primary key,
  id_op bigint,
  cod_op bigint,
  numero_op text,
  dt_emissao date,
  dt_previsao date,
  status text,
  cod_prod bigint,
  quantidade numeric,
  synced_at timestamptz default now()
);

alter table omie_orders_production
  add column if not exists id_op bigint,
  add column if not exists cod_op bigint,
  add column if not exists numero_op text,
  add column if not exists dt_emissao date,
  add column if not exists dt_previsao date,
  add column if not exists status text,
  add column if not exists cod_prod bigint,
  add column if not exists quantidade numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_orders_production_synced on omie_orders_production (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_service_contracts  (phase 7, tier industry)
-- Recurring services (SaaS, monthly fee)
-- Endpoint: servicos/contratoservico/ListarContratos
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_service_contracts (
  omie_id text primary key,
  cod_ctr bigint,
  numero_ctr text,
  cod_cliente bigint,
  dt_validade date,
  periodicidade text,
  synced_at timestamptz default now()
);

alter table omie_service_contracts
  add column if not exists cod_ctr bigint,
  add column if not exists numero_ctr text,
  add column if not exists cod_cliente bigint,
  add column if not exists dt_validade date,
  add column if not exists periodicidade text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_service_contracts_synced on omie_service_contracts (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_cte  (phase 7, tier industry)
-- Shipping company CT-e
-- Endpoint: produtos/cte/ListarCTE
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_cte (
  omie_id text primary key,
  id_cte bigint,
  cod_cte bigint,
  numero_cte text,
  serie text,
  chave_cte text,
  dt_emissao date,
  valor numeric,
  synced_at timestamptz default now()
);

alter table omie_cte
  add column if not exists id_cte bigint,
  add column if not exists cod_cte bigint,
  add column if not exists numero_cte text,
  add column if not exists serie text,
  add column if not exists chave_cte text,
  add column if not exists dt_emissao date,
  add column if not exists valor numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_cte_synced on omie_cte (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_fiscal_coupon  (phase 7, tier industry)
-- Retail POS NFC-e / SAT
-- Endpoint: produtos/nfceconsultar/ListarNFCE
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_fiscal_coupon (
  omie_id text primary key,
  id_nfce bigint,
  cod_nfce bigint,
  numero_nfce text,
  chave_nfce text,
  dt_emissao date,
  valor_nfce numeric,
  synced_at timestamptz default now()
);

alter table omie_fiscal_coupon
  add column if not exists id_nfce bigint,
  add column if not exists cod_nfce bigint,
  add column if not exists numero_nfce text,
  add column if not exists chave_nfce text,
  add column if not exists dt_emissao date,
  add column if not exists valor_nfce numeric,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_fiscal_coupon_synced on omie_fiscal_coupon (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_tags  (phase 7, tier industry)
-- Tags for clients / suppliers
-- Endpoint: geral/tags/ListarTags
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_tags (
  omie_id text primary key,
  cod_tag bigint,
  tag text,
  synced_at timestamptz default now()
);

alter table omie_tags
  add column if not exists cod_tag bigint,
  add column if not exists tag text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_tags_synced on omie_tags (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_caracteristicas_clientes  (phase 7, tier industry)
-- Custom fields on clients
-- Endpoint: geral/clientescaract/ListarCaract
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_caracteristicas_clientes (
  omie_id text primary key,
  cod_caract bigint,
  nome text,
  tipo text,
  synced_at timestamptz default now()
);

alter table omie_caracteristicas_clientes
  add column if not exists cod_caract bigint,
  add column if not exists nome text,
  add column if not exists tipo text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_caracteristicas_clientes_synced on omie_caracteristicas_clientes (synced_at);

-- ──────────────────────────────────────────────────────────────────
-- omie_product_characteristics  (phase 7, tier industry)
-- Custom field definitions on products
-- Endpoint: geral/produtoscaract/ListarCaract
-- ──────────────────────────────────────────────────────────────────
create table if not exists omie_product_characteristics (
  omie_id text primary key,
  cod_caract bigint,
  nome text,
  tipo text,
  synced_at timestamptz default now()
);

alter table omie_product_characteristics
  add column if not exists cod_caract bigint,
  add column if not exists nome text,
  add column if not exists tipo text,
  add column if not exists synced_at timestamptz default now();

create index if not exists idx_omie_product_characteristics_synced on omie_product_characteristics (synced_at);

-- ── Foreign keys (deferred until every parent table exists) ──────

-- omie_client_tags.codigo_cliente_omie → omie_clients.codigo_cliente_omie
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_client_tags_codigo_cliente_omie'
  ) then
    alter table omie_client_tags
      add constraint fk_omie_client_tags_codigo_cliente_omie
      foreign key (codigo_cliente_omie) references omie_clients (codigo_cliente_omie) on delete cascade;
  end if;
end $$;

-- omie_client_caracteristicas.codigo_cliente_omie → omie_clients.codigo_cliente_omie
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_client_caracteristicas_codigo_cliente_omie'
  ) then
    alter table omie_client_caracteristicas
      add constraint fk_omie_client_caracteristicas_codigo_cliente_omie
      foreign key (codigo_cliente_omie) references omie_clients (codigo_cliente_omie) on delete cascade;
  end if;
end $$;

-- omie_client_contatos.codigo_cliente_omie → omie_clients.codigo_cliente_omie
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_client_contatos_codigo_cliente_omie'
  ) then
    alter table omie_client_contatos
      add constraint fk_omie_client_contatos_codigo_cliente_omie
      foreign key (codigo_cliente_omie) references omie_clients (codigo_cliente_omie) on delete cascade;
  end if;
end $$;

-- omie_order_items.codigo_pedido → omie_orders.codigo_pedido
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_order_items_codigo_pedido'
  ) then
    alter table omie_order_items
      add constraint fk_omie_order_items_codigo_pedido
      foreign key (codigo_pedido) references omie_orders (codigo_pedido) on delete cascade;
  end if;
end $$;

-- omie_order_lancamentos.codigo_pedido → omie_orders.codigo_pedido
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_order_lancamentos_codigo_pedido'
  ) then
    alter table omie_order_lancamentos
      add constraint fk_omie_order_lancamentos_codigo_pedido
      foreign key (codigo_pedido) references omie_orders (codigo_pedido) on delete cascade;
  end if;
end $$;

-- omie_service_order_items.codigo_os → omie_service_orders.codigo_os
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_service_order_items_codigo_os'
  ) then
    alter table omie_service_order_items
      add constraint fk_omie_service_order_items_codigo_os
      foreign key (codigo_os) references omie_service_orders (codigo_os) on delete cascade;
  end if;
end $$;

-- omie_service_order_parcels.codigo_os → omie_service_orders.codigo_os
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_service_order_parcels_codigo_os'
  ) then
    alter table omie_service_order_parcels
      add constraint fk_omie_service_order_parcels_codigo_os
      foreign key (codigo_os) references omie_service_orders (codigo_os) on delete cascade;
  end if;
end $$;

-- omie_product_caract_values.codigo_produto → omie_products.codigo_produto
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_product_caract_values_codigo_produto'
  ) then
    alter table omie_product_caract_values
      add constraint fk_omie_product_caract_values_codigo_produto
      foreign key (codigo_produto) references omie_products (codigo_produto) on delete cascade;
  end if;
end $$;

-- omie_product_tags.codigo_produto → omie_products.codigo_produto
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_product_tags_codigo_produto'
  ) then
    alter table omie_product_tags
      add constraint fk_omie_product_tags_codigo_produto
      foreign key (codigo_produto) references omie_products (codigo_produto) on delete cascade;
  end if;
end $$;

-- omie_product_images.codigo_produto → omie_products.codigo_produto
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_product_images_codigo_produto'
  ) then
    alter table omie_product_images
      add constraint fk_omie_product_images_codigo_produto
      foreign key (codigo_produto) references omie_products (codigo_produto) on delete cascade;
  end if;
end $$;

-- omie_financial_movements_categorias.parent_omie_id → omie_financial_movements.omie_id
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_financial_movements_categorias_parent_omie_id'
  ) then
    alter table omie_financial_movements_categorias
      add constraint fk_omie_financial_movements_categorias_parent_omie_id
      foreign key (parent_omie_id) references omie_financial_movements (omie_id) on delete cascade;
  end if;
end $$;

-- omie_estoque_movimentos_lancamentos.parent_omie_id → omie_estoque_movimentos.omie_id
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_estoque_movimentos_lancamentos_parent_omie_id'
  ) then
    alter table omie_estoque_movimentos_lancamentos
      add constraint fk_omie_estoque_movimentos_lancamentos_parent_omie_id
      foreign key (parent_omie_id) references omie_estoque_movimentos (omie_id) on delete cascade;
  end if;
end $$;

-- omie_nfe_items.parent_omie_id → omie_nfe.omie_id
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_omie_nfe_items_parent_omie_id'
  ) then
    alter table omie_nfe_items
      add constraint fk_omie_nfe_items_parent_omie_id
      foreign key (parent_omie_id) references omie_nfe (omie_id) on delete cascade;
  end if;
end $$;

-- ── sync_log ─────────────────────────────────────────────────────
create table if not exists sync_log (
  id              bigserial primary key,
  entity          text not null,
  records_synced  integer default 0,
  started_at      timestamptz,
  finished_at     timestamptz default now(),
  status          text not null,
  error           text
);

create index if not exists idx_sync_log_entity on sync_log (entity, finished_at desc);
create index if not exists idx_sync_log_status on sync_log (status);

-- ── Row Level Security (required by Supabase) ────────────────────
alter table omie_clients enable row level security;
alter table omie_client_tags enable row level security;
alter table omie_client_caracteristicas enable row level security;
alter table omie_client_contatos enable row level security;
alter table omie_orders enable row level security;
alter table omie_order_items enable row level security;
alter table omie_order_lancamentos enable row level security;
alter table omie_accounts_receivable enable row level security;
alter table omie_accounts_payable enable row level security;
alter table omie_service_orders enable row level security;
alter table omie_service_order_items enable row level security;
alter table omie_service_order_parcels enable row level security;
alter table omie_products enable row level security;
alter table omie_product_caract_values enable row level security;
alter table omie_product_tags enable row level security;
alter table omie_product_images enable row level security;
alter table omie_crm_opportunities enable row level security;
alter table omie_crm_activities enable row level security;
alter table omie_categories enable row level security;
alter table omie_departments enable row level security;
alter table omie_projects enable row level security;
alter table omie_document_types enable row level security;
alter table omie_units enable row level security;
alter table omie_familias_produtos enable row level security;
alter table omie_billing_stages enable row level security;
alter table omie_vendedores enable row level security;
alter table omie_stock_locations enable row level security;
alter table omie_banks enable row level security;
alter table omie_parcelas enable row level security;
alter table omie_price_tables enable row level security;
alter table omie_crm_phases enable row level security;
alter table omie_crm_status enable row level security;
alter table omie_crm_origens enable row level security;
alter table omie_current_accounts enable row level security;
alter table omie_financial_movements enable row level security;
alter table omie_financial_movements_categorias enable row level security;
alter table omie_current_account_transactions enable row level security;
alter table omie_estoque_posicao enable row level security;
alter table omie_estoque_movimentos enable row level security;
alter table omie_estoque_movimentos_lancamentos enable row level security;
alter table omie_orders_purchase enable row level security;
alter table omie_notas_entrada enable row level security;
alter table omie_nfe enable row level security;
alter table omie_nfe_items enable row level security;
alter table omie_crm_contatos enable row level security;
alter table omie_products_variation enable row level security;
alter table omie_products_kit enable row level security;
alter table omie_products_lot enable row level security;
alter table omie_products_structure enable row level security;
alter table omie_orders_production enable row level security;
alter table omie_service_contracts enable row level security;
alter table omie_cte enable row level security;
alter table omie_fiscal_coupon enable row level security;
alter table omie_tags enable row level security;
alter table omie_caracteristicas_clientes enable row level security;
alter table omie_product_characteristics enable row level security;
alter table sync_log enable row level security;

-- ── Sanity check ──────────────────────────────────────────────────
select table_name, column_name, data_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name like 'omie_%'
  order by table_name, ordinal_position;
