#!/usr/bin/env node
'use strict';

/**
 * Generate `config/schema.sql` directly from `config/omie-tables.js`.
 *
 *   node scripts/generate-schema.js > config/schema.sql
 *
 * Output is a single SQL file that:
 *   - drops every old `raw`/jsonb column and stops using GENERATED columns
 *   - declares one Postgres column per declared Omie field
 *   - creates a child table for every `children[]` array definition
 *   - applies foreign-key constraints from each child table to its parent
 *   - sets sensible btree indexes on synced_at and (for child tables)
 *     the FK column
 *
 * Re-run after any change to `config/omie-tables.js`.
 */

const path = require('path');
const { TABLES } = require(path.join('..', 'config', 'omie-tables'));

// ─── helpers ────────────────────────────────────────────────────────────

const SQL_TYPE_MAP = {
  text: 'text',
  numeric: 'numeric',
  bigint: 'bigint',
  date: 'date',
  timestamptz: 'timestamptz',
  boolean: 'boolean',
  boolean_inverted: 'boolean',
};

function sqlType(col) {
  const t = col.type || 'text';
  const mapped = SQL_TYPE_MAP[t];
  if (!mapped) throw new Error(`Unknown column type ${t} on ${col.name}`);
  return mapped;
}

function quoteIdent(name) {
  return /^[a-z_][a-z0-9_]*$/.test(name) ? name : `"${name}"`;
}

function camelOrSnakeToSnake(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[\s\-]+/g, '_')
    .toLowerCase();
}

function pkColumnName(entryOrChild) {
  if (entryOrChild.pkColumn) return entryOrChild.pkColumn;
  if (entryOrChild.parentRefColumn) return 'omie_id';

  if (entryOrChild.legacy) {
    const firstId = entryOrChild.idFields && entryOrChild.idFields[0];
    if (firstId) {
      if (entryOrChild.columns) {
        const match = entryOrChild.columns.find((c) => c.from === firstId);
        if (match) return match.name;
      }
      if (!firstId.includes('.') && /^[a-z_][a-z0-9_]*$/i.test(firstId)) {
        return camelOrSnakeToSnake(firstId);
      }
    }
  }
  return 'omie_id';
}

function effectivePkType(entryOrChild) {
  if (entryOrChild.pkType) return entryOrChild.pkType;
  if (entryOrChild.parentRefColumn) return 'text';
  const pkCol = pkColumnName(entryOrChild);
  if (pkCol === 'omie_id') return 'text';
  const def = (entryOrChild.columns || []).find((c) => c.name === pkCol);
  if (def && def.type === 'bigint') return 'bigint';
  return 'text';
}

// ─── emit ───────────────────────────────────────────────────────────────

const lines = [];
const FK_DEFERRED = []; // FK statements added after all tables are created.

lines.push(
  '-- ============================================================',
  '-- config/schema.sql — generated by scripts/generate-schema.js',
  '--',
  '-- Single source of truth for the Omie → Supabase database.',
  '-- Re-run after any change to config/omie-tables.js.',
  '--',
  '-- Every Omie field is a typed, real Postgres column. NO raw / NO',
  '-- jsonb columns. Arrays of objects (line items, characteristics,',
  '-- etc.) are pivoted into dedicated child tables linked via FK.',
  '--',
  '-- This file is idempotent — `create table if not exists` and',
  '-- `add column if not exists` everywhere. Designed to be pasted',
  '-- straight into the Supabase SQL Editor on a fresh database.',
  '-- ============================================================',
  '',
);

let parentCount = 0;
let childCount = 0;
let columnCount = 0;

// Every public table needs RLS turned on for Supabase. The service role
// bypasses RLS, so the sync pipeline works without policies; downstream
// readers can add policies later as needed.
const RLS_TABLES = [];

for (const entry of TABLES) {
  if (entry.enabled === false) continue;
  parentCount++;
  RLS_TABLES.push(entry.table);

  const t = quoteIdent(entry.table);
  const pkName = pkColumnName(entry);
  const pkType = effectivePkType(entry);

  const phaseLabel = entry.legacy ? 'phase 0 (legacy)' : `phase ${entry.phase}`;
  lines.push(
    '-- ──────────────────────────────────────────────────────────────────',
    `-- ${entry.table}  (${phaseLabel}, tier ${entry.tier})`,
    `-- ${entry.purpose}`,
    `-- Endpoint: ${entry.endpoint}/${entry.action}`,
    '-- ──────────────────────────────────────────────────────────────────',
  );

  // Build column definitions for the CREATE TABLE body. The PK is
  // emitted as the first column. If the PK column is also declared
  // in `columns`, the column's declared type wins.
  const pkColumnDef = (entry.columns || []).find((c) => c.name === pkName);
  const pkSqlType = pkColumnDef ? sqlType(pkColumnDef) : pkType;

  const inlineCols = [];
  inlineCols.push(`  ${quoteIdent(pkName)} ${pkSqlType} primary key`);

  const declared = new Set([pkName]);
  for (const col of entry.columns || []) {
    if (declared.has(col.name)) continue;
    declared.add(col.name);
    columnCount++;
    inlineCols.push(`  ${quoteIdent(col.name)} ${sqlType(col)}`);
  }
  inlineCols.push('  synced_at timestamptz default now()');

  lines.push(`create table if not exists ${t} (`);
  lines.push(inlineCols.join(',\n'));
  lines.push(');');
  lines.push('');

  // `add column if not exists` block — safe re-run on existing DBs.
  const adds = [];
  for (const col of entry.columns || []) {
    if (col.name === pkName) continue;
    adds.push(`  add column if not exists ${quoteIdent(col.name)} ${sqlType(col)}`);
  }
  adds.push(`  add column if not exists synced_at timestamptz default now()`);
  if (adds.length) {
    lines.push(`alter table ${t}`);
    lines.push(adds.join(',\n') + ';');
    lines.push('');
  }

  lines.push(
    `create index if not exists idx_${entry.table}_synced on ${t} (synced_at);`,
    '',
  );

  // ── child tables ───────────────────────────────────────────────
  for (const child of entry.children || []) {
    childCount++;
    RLS_TABLES.push(child.table);
    const ct = quoteIdent(child.table);

    // Child's own PK is always `omie_id text` for resilience.
    const cpkName = pkColumnName(child);
    const cpkSqlType = effectivePkType(child) === 'bigint' ? 'bigint' : 'text';

    // FK column on the child holds the parent's PK value.
    // For legacy parents the column is named after the natural PK
    // (e.g. `codigo_pedido`). For registry parents we still allow a
    // descriptive name via parentRefColumn — its TYPE matches the
    // parent PK's type (so when the parent PK is `omie_id text`,
    // the child's FK column is also text).
    const fkCol = child.parentRefColumn || pkName;
    const fkSqlType = pkSqlType;

    lines.push(
      `-- child of ${entry.table}: array \`${child.listFrom}\``,
    );

    const childInline = [];
    childInline.push(`  ${quoteIdent(cpkName)} ${cpkSqlType} not null`);
    if (fkCol !== cpkName) {
      childInline.push(`  ${quoteIdent(fkCol)} ${fkSqlType} not null`);
    }
    const childDeclared = new Set([cpkName, fkCol]);
    for (const col of child.columns || []) {
      if (childDeclared.has(col.name)) continue;
      childDeclared.add(col.name);
      columnCount++;
      childInline.push(`  ${quoteIdent(col.name)} ${sqlType(col)}`);
    }
    childInline.push('  synced_at timestamptz default now()');
    if (fkCol !== cpkName) {
      childInline.push(`  primary key (${quoteIdent(fkCol)}, ${quoteIdent(cpkName)})`);
    } else {
      childInline.push(`  primary key (${quoteIdent(cpkName)})`);
    }

    lines.push(`create table if not exists ${ct} (`);
    lines.push(childInline.join(',\n'));
    lines.push(');');
    lines.push('');

    const childAdds = [];
    for (const col of child.columns || []) {
      if (col.name === cpkName || col.name === fkCol) continue;
      childAdds.push(`  add column if not exists ${quoteIdent(col.name)} ${sqlType(col)}`);
    }
    childAdds.push(`  add column if not exists synced_at timestamptz default now()`);
    if (childAdds.length) {
      lines.push(`alter table ${ct}`);
      lines.push(childAdds.join(',\n') + ';');
      lines.push('');
    }

    lines.push(
      `create index if not exists idx_${child.table}_${fkCol} on ${ct} (${quoteIdent(fkCol)});`,
      `create index if not exists idx_${child.table}_synced on ${ct} (synced_at);`,
      '',
    );

    // Foreign key — emitted after every table is created.
    FK_DEFERRED.push(
      `-- ${child.table}.${fkCol} → ${entry.table}.${pkName}`,
      `do $$ begin`,
      `  if not exists (`,
      `    select 1 from pg_constraint where conname = 'fk_${child.table}_${fkCol}'`,
      `  ) then`,
      `    alter table ${ct}`,
      `      add constraint fk_${child.table}_${fkCol}`,
      `      foreign key (${quoteIdent(fkCol)}) references ${t} (${quoteIdent(pkName)}) on delete cascade;`,
      `  end if;`,
      `end $$;`,
      '',
    );
  }
}

// FKs after every table has been created.
lines.push(
  '-- ── Foreign keys (deferred until every parent table exists) ──────',
  '',
);
lines.push(...FK_DEFERRED);

// sync_log audit table.
lines.push(
  '-- ── sync_log ─────────────────────────────────────────────────────',
  'create table if not exists sync_log (',
  '  id              bigserial primary key,',
  '  entity          text not null,',
  '  records_synced  integer default 0,',
  '  started_at      timestamptz,',
  '  finished_at     timestamptz default now(),',
  '  status          text not null,',
  '  error           text',
  ');',
  '',
  'create index if not exists idx_sync_log_entity on sync_log (entity, finished_at desc);',
  'create index if not exists idx_sync_log_status on sync_log (status);',
  '',
);

// Row Level Security. Supabase shows a security warning whenever a
// public-schema table has RLS disabled. The service role used by the
// sync pipeline bypasses RLS, so no policies are needed for the sync
// itself; add explicit policies later if you want anon/authenticated
// reads.
lines.push(
  '-- ── Row Level Security (required by Supabase) ────────────────────',
);
for (const t of [...RLS_TABLES, 'sync_log']) {
  lines.push(`alter table ${quoteIdent(t)} enable row level security;`);
}
lines.push('');
lines.push(
  '-- ── Sanity check ──────────────────────────────────────────────────',
  "select table_name, column_name, data_type",
  '  from information_schema.columns',
  "  where table_schema = 'public'",
  "    and table_name like 'omie_%'",
  '  order by table_name, ordinal_position;',
);

process.stderr.write(
  `Generated config/schema.sql: ${parentCount} parent tables, ` +
    `${childCount} child tables, ${columnCount} typed columns.\n`,
);
process.stdout.write(lines.join('\n') + '\n');
